export const RECOVERED_ASSETS = {
  editorial: {
    homeHero: "/manus-storage/editorial-home-hero_67cba1c9.jpg",
    homeSkincare: "/manus-storage/editorial-home-skincare_7e8e0204.jpg",
    skinTest: "/manus-storage/editorial-skin-test_d56a3a43.png",
    storyDetail: "/manus-storage/editorial-story-detail_797f9e01.jpg",
    storyPortrait: "/manus-storage/editorial-story-portrait_a73126e1.jpg",
    storyWide: "/manus-storage/editorial-story-wide_14bfe783.jpg",
  },
  products: {
    serum: "/manus-storage/product-hautpflege-individuelle-serum-creme_59b5acd0.jpg",
    creme: "/manus-storage/product-hautpflege-erstelle-deine-creme_87ae5318.jpg",
    cleanerGel: "/manus-storage/product-cleaner-reinigungsgel_9a8e77c6.png",
    cleanerMilk: "/manus-storage/product-cleaner-reinigungs-milch_7d3e023f.png",
    peelingAha: "/manus-storage/product-peeling-aha-pha-peeling_333cbf38.png",
    peelingBha: "/manus-storage/product-peeling-bha-azelainsaure-peeling_2bd366e6.png",
    sunscreen: "/manus-storage/product-general-sonnenschutzfluid-spf-50_870ad93a.jpg",
    baseCreme: "/manus-storage/product-creme-basic-basiscreme_6b980eea.jpg",
    baseCremeRich: "/manus-storage/product-creme-basic-basiscreme-rich_564937b6.webp",
    baseSerum: "/manus-storage/product-serum-basic-basiscreme-serum_2fc5bae8.jpg",
  },
  ingredients: {
    creme: {
      willow: "/manus-storage/product-ingredient-creme-weidenrindenextrakt_0bb34194.png",
      niacinamide: "/manus-storage/product-ingredient-creme-niacinamide_cc34ad82.png",
      vitaminc: "/manus-storage/product-ingredient-creme-vitaminkomplex_13a7064d.png",
      retinol: "/manus-storage/product-ingredient-creme-retinolkomplex_f783a663.png",
      spilanthol: "/manus-storage/product-ingredient-creme-spilantholkomplex-creme_37a25a01.png",
      mallow: "/manus-storage/product-ingredient-creme-malvenextrakt_c9e29a4e.png",
      horsechestnut: "/manus-storage/product-ingredient-creme-rosskastanienextrakt_25117b5a.png",
      rosehip: "/manus-storage/product-ingredient-creme-wildrosenol_a138d80c.png",
      seabuckthorn: "/manus-storage/product-ingredient-creme-sanddornol_2707a8c2.png",
      grapeseed: "/manus-storage/product-ingredient-creme-traubenkernol_f6f9b948.png",
      thistle: "/manus-storage/product-ingredient-creme-distelol_8c32e19d.png",
      algae: "/manus-storage/product-ingredient-creme-algenextrakt_2dd0d1ef.png",
      hyaluronic: "/manus-storage/product-ingredient-creme-hyaluronkomplex_65604b67.png",
    },
    serum: {
      willow: "/manus-storage/product-ingredient-serum-weidenrindenextrakt-serum_df236911.png",
      niacinamide: "/manus-storage/product-ingredient-serum-niacinamide-serum_2e906fce.png",
      vitaminc: "/manus-storage/product-ingredient-serum-vitaminkomplex-serum_dc12670a.png",
      retinol: "/manus-storage/product-ingredient-serum-retinolkomplex-serum_556455dc.png",
      spilanthol: "/manus-storage/product-ingredient-serum-spilantholkomplex_07997302.png",
      mallow: "/manus-storage/product-ingredient-serum-malvenextrakt-serum_9b59eeb9.png",
      horsechestnut: "/manus-storage/product-ingredient-serum-rosskastanienextrakt-serum_448723aa.png",
      algae: "/manus-storage/product-ingredient-serum-algenextrakt-serum_0220c3ff.png",
      hyaluronic: "/manus-storage/product-ingredient-serum-hyaluronkomplex-serum_61df0621.png",
    },
  },
} as const;
